# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "db08c9d16e52101fd52ec34b8de1321b"
name = "ZionSEO"
handle = "zionseo"
application_url = "https://childhood-yorkshire-pencil-pockets.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[app_proxy]
url = "https://583cde0ade9b.ngrok-free.app/app/api/proxy"
subpath = "llms-txt"
prefix = "a"

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_content,write_app_proxy,write_online_store_navigation,read_online_store_navigation,"

[auth]
redirect_urls = ["https://childhood-yorkshire-pencil-pockets.trycloudflare.com/auth/callback", "https://childhood-yorkshire-pencil-pockets.trycloudflare.com/auth/shopify/callback", "https://childhood-yorkshire-pencil-pockets.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
